### PR TITLE
Fix nil pointer in screenshot

### LINKED ISSUE #631: Panic in Screenshot
**Rod Version:** v0.107.2

## What you got

page.go:371 throws "invalid memory address or nil pointer deference"

image

I think "metrics" or "CSSContentSize" is nil. This happens in a customer environment, so I can't repro the issue when I want. I see the panic from the logs. I will try to do some debug but maybe you already have an idea which one might be nil? 

## What you expected to see

Instead of panic, it should return error.

## What have you tried to solve the question

I can add nil check for metrics and CSSContentSize.

### PR DESCRIPTION
**Pull request by alexferrari88**
This PR is equivalent to #632 but has test coverage.
It fixes #631

### CODE REVIEW

File: page_test.go [hunk 1]
```diff
@@ -647,6 +648,13 @@ func TestScreenshotFullPage(t *testing.T) {
 		g.mc.stubErr(1, proto.EmulationSetDeviceMetricsOverride{})
 		p.MustScreenshotFullPage()
 	})
+
+	g.Panic(func() {
+		g.mc.stub(1, proto.PageGetLayoutMetrics{}, func(send StubSend) (gson.JSON, error) {
+			return gson.New(proto.PageGetLayoutMetricsResult{}), nil
+		})
+		p.MustScreenshotFullPage()
```
Comment (ysmood) [inline page_test.go:656]: Should use `p.ScreenshotFullPage`

**Review by ysmood — CHANGES_REQUESTED** [review]

File: page_test.go (hunk 1 above)
Comment (alexferrari88) [reply page_test.go:656]: thank you for the review. Unfortunately, there are two problems with this suggestion:
1) `p.ScreenshotFullPage undefined (type *rod.Page has no field or method ScreenshotFullPage)` so maybe you meant `p.Screenshot(true, nil)`?
2) If I don't use the Must method, the `panic` won't be triggered hence the `g.Panic()` I'm wrapping this call in.

**Comment by ysmood** [comment]
The PR looks good, can you pull the latest master and resolve the conflicts?

**Comment by alexferrari88** [comment]
> The PR looks good, can you pull the latest master and resolve the conflicts?

I think I have managed...

**Comment by ysmood** [comment]
It's still not in sync with the master:

Screenshot_2022-08-28-13-34-15-19_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by alexferrari88** [comment]
I guess it didn't refresh the page after I merged the changes :)
It should be good to go now

File: lib/assets/assets.go [hunk 2]
```diff
@@ -1,4 +1,3 @@
-// Package assets is generated by "lib/assets/generate"
```
Comment (ysmood) [inline lib/assets/assets.go:1]: Can you remove this change? I have fixed the master, ypu don't need it anymore.

**Review by ysmood — CHANGES_REQUESTED** [review]

File: lib/assets/assets.go (hunk 2 above)
Comment (alexferrari88) [reply lib/assets/assets.go:1]: strange because I have already removed it. See [here](https://github.com/alexferrari88/rod/blob/bug/631/lib/assets/assets.go).

Comment (alexferrari88) [reply lib/assets/assets.go]: I rebased with master, solved the conflict, and now it should be as you said.

**Review by ysmood — APPROVED** [review]
