### PR TITLE
Remove user-data-dir, after launcher exited.

### LINKED ISSUE #181: user-data-dir still exists after browser is closed
**Rod Version:** v0.49.5

## To Reproduce

```go
package main

import (
	"fmt"
	"os"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
)

const tempdir = "tempdir"

func main() {
	_, err := os.Stat(tempdir)
	fmt.Println(err)
	demo()

	_, err = os.Stat(tempdir)
	fmt.Println(err)
}

func demo() {
	url := launcher.New().UserDataDir(tempdir).Launch()
	browser := rod.New().ControlURL(url).Connect().Trace(true)
	defer browser.Close()
	page := browser.Page("https://google.com")
	defer page.Close()
	page.WaitLoad()
}

```

Output:
```
stat tempdir: no such file or directory
<nil> # should be the same as above
```

## Expected behavior
Rod claims that it deletes the data dir when the browser is closed:
https://github.com/go-rod/rod/blob/44b9c7239bee6a02a590a1f22453087ee8900856/lib/launcher/proxy.go#L38

I expected the "tempdir" to get deleted after the browser is closed.

## Actual result

The tempdir still exists after calling close.

## How I found this
When using `lib/launcher.New()` to create the new browser the user-data-dir is randomized:
https://github.com/go-rod/rod/blob/37a628f131d417f0b83cc2f42da3b2664113bfeb/lib/launcher/launcher.go#L43
This means a new Directory is created for every created browser, because these are never cleaned up they can use up some significant amount of storage on long running programs (this is after a few days with multiple concurrent browsers, and regular browser restarts).

```
$ du -h rod
... [Redacted] ...
28K	rod/user-data/58a27be17dbf9ee1/Default/Local Storage
65M	rod/user-data/58a27be17dbf9ee1/Default
65M	rod/user-data/58a27be17dbf9ee1
4.1M	rod/user-data/baf0f3170e185ce9/BrowserMetrics
4.1M	rod/user-data/baf0f3170e185ce9
4.1M	rod/user-data/bec95cc2177dd64f/BrowserMetrics
4.1M	rod/user-data/bec95cc2177dd64f
66G	rod/user-data
66G	rod

```
These 66GB of data lead to my disk running out of storage:
```
$ df -h
Filesystem                   Size  Used Avail Use% Mounted on
...
/dev/mapper/server--vg-root  467G  443G     0 100% /
...
```
Which then leads to the program not being able to open any new browser instance:
```
/snap/chromium/1260/bin/desktop-launch: line 373: cannot create temp file for here-document: No spac>
[0810/130517.860904:WARNING:discardable_shared_memory_manager.cc(194)] Less than 64MB of free space >
[0810/130517.864102:FATAL:memory.cc(40)] Out of memory. size=131072
```

### PR DESCRIPTION
**Pull request by lu4p**
Fix #181 

```go
package main

import (
	"fmt"
	"os"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
)

const tempdir = "tempdir"

func main() {
	_, err := os.Stat(tempdir)
	fmt.Println(err)
	demo()

	_, err = os.Stat(tempdir)
	fmt.Println(err)
}

func demo() {
	launcher := launcher.New().UserDataDir(tempdir)
	defer launcher.Cleanup()
	url := launcher.Launch()

	browser := rod.New().ControlURL(url).Connect().Trace(true)
	defer browser.Close()

	page := browser.Page("https://google.com")
	defer page.Close()
	page.WaitLoad()
}


```

Output: 
```
stat tempdir: no such file or directory
Remove /home/luap/lakbot/test/tempdir
stat tempdir: no such file or directory
```

I don't like the Cleanup function, but else the program exits before waiting until the browser process exited, maybe someone has an idea how to work around this.

### CODE REVIEW

File: lib/launcher/launcher.go [hunk 1]
```diff
@@ -347,6 +348,17 @@ func (l *Launcher) PID() int {
 	return l.pid
 }
 
+// Cleanup wait until the Browser exits and release related resources
+func (l *Launcher) Cleanup() {
+	<-l.exit
+	if _, has := l.Get("keep-user-data-dir"); !has {
+		dir, _ := l.Get("user-data-dir")
+		fmt.Println(utils.C("Remove", "cyan"), dir)
```
Comment (ysmood) [inline lib/launcher/launcher.go:356]: should use configurable log like other parts, search `l.log`:

https://github.com/go-rod/rod/blob/44b9c72/lib/launcher/launcher.go#L360

**Comment by lu4p** [comment]
@ysmood Done

**Comment by ysmood** [comment]
Nice job, can you also update the example code under this line:

https://github.com/go-rod/rod/blob/44b9c72/examples_test.go#L23

 `defer launcher.Cleanup()`

**Comment by lu4p** [comment]
@ysmood How would I do that? As there is no laucher Instance.

**Comment by ysmood** [comment]
How about under this line?

https://github.com/go-rod/rod/blob/dc7fcd1/examples_test.go#L96

**Comment by lu4p** [comment]
@ysmood Done

**Comment by lu4p** [comment]
@ysmood This should probably also be the default behaviour when creating a new instance using just `browser := rod.New().Connect()`, I don't know how this could be achived.

**Comment by ysmood** [comment]
`rod.New().Connect()` is just a shortcut, it's better to separate the launch and connect into 2 steps. I don't have a better way to abstract them. Because a lot of people don't use local browser at all. They don't have the permission to remove the remote tmpdir at all.

**Comment by ysmood** [comment]
BTW, the `<- l.exit` is really a nice idea 👍

**Comment by lu4p** [comment]
> `rod.New().Connect()` is just a shortcut, it's better to separate the launch and connect into 2 steps. I don't have a better way to abstract them. Because a lot of people don't use local browser at all. They don't have the permission to remove the remote tmpdir at all.

@ysmood Then maybe refactor New to `(*rod.Browser).New(url string) *rod.Browser` and remove `(*rod.Browser).ControlURL(url string) *rod.Browser`

**Comment by ysmood** [comment]
Actually, that's how the old code works. For beginners, it's better to keep things simple. As long as it's still configurable with just several extra lines I think it's ok to abstract it away.

If you have a strong reason to do it, we can raise an issue and let more users vote what's better.
